name: Build and Publish

on:
  push:
    branches:
      - dev
  # pull_request:
  #   branches:
  #     - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest  # Убираем матрицу для упрощения
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install
        timeout-minutes: 60

      - name: Build the app
        run: npm run build -- -l --publish=never 

      - name: List files after build
        run: |
          echo "Files in dist directory:"
          ls -R dist/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: netmax-build  # Убираем матрицу из имени артефакта
          path: dist/

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: netmax-build  # Используем то же имя, что и при загрузке
          path: ./dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
